# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmd = "npm ci && cd backend && npm ci"

[phases.build]
cmd = "cd backend && npm run build"

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
